# Change these first
owner: ArturooT # Your GitHub organization or username, where this repository lives
repo: telecomm # The name of this repository

sites:
  - name: Telecomm
    url: https://www.telecomm.gob.mx
  - name: Telecomm-ServerInterno
    url: https://www.telecomm.gob.mx/portal
  - name: GOBMX
    url: https://www.gob.mx
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /telecomm
  logoUrl: https://telecomm.gob.mx/gobmx/wp-content/uploads/2022/02/logo-telecomm.png
  name: Telecomm-Monitor
  introTitle: "Monitor para portal web institucional **TELECOMM.GOB.MX**"
  introMessage: Esta es una página de monitoreo de servicio web (apache|nginx) que utiliza datos en **tiempo real** del repositorio de GitHub.data obtenidos del portal de telecomm.gob.mx. No se requiere servidor, solo GitHub Actions, Issues y Pages.
  navbar:
    - title: Estatus
      href: https://arturoot.github.io/telecomm/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
